name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Sync with upstream
        uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: original-owner-name
          repo: original-repo-name
